### ISSUE TITLE
Cannot nest 'jhipster-scout-presentation/src/main/resources' inside 'jhipster-scout-presentation/src'.

### ISSUE THREAD

**Issue by jmini** [BSI-Business-Systems-Integration-AG/demo-jhipster-democamp-2017#1]
I am following the step by step tutorial here: [README.md](https://github.com/BSI-Business-Systems-Integration-AG/demo-jhipster-democamp-2017/blob/master/jhipster-ide-presentation/README.md)
After Step 4 (run `jhipster` and `mvnw`), I have tried to do Step 6 (I have skipped Step 5 for the moment, I wanted to check if I can start the empty generated app).

I had the following problem in Eclipse as message box. Here is the corresponding text copy-pasted from the error log view:

```
eclipse.buildId=4.7.0.I20170308-2000
java.version=1.8.0_102
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.jdt.core
Error
Mon Apr 10 22:23:50 CEST 2017
Cannot nest 'jhipster-scout-presentation/src/main/resources' inside 'jhipster-scout-presentation/src'. To enable the nesting exclude 'main/' from 'jhipster-scout-presentation/src'
```

**Workaround / Solution:**

Remove following line from `/jhipster-scout-presentation/.classpath`:
```
	<classpathentry kind="src" path="src"/>
```

Update maven project (ALT + F5)

Add manually the line:
```
	<classpathentry kind="src" path="src/model"/>
```
(otherwise you do not see the model file as source code anylonger)

@colameo is this a known issue?

**Comment by colameo** [comment]
...you need first to remove the already defined/mapped "src" folder, apply and re-add src and output folders. I do not want to explain all micro steps as I am also improving a lot in this area so that it is not needed anymore...
