### ISSUE TITLE
Too many ids ?

### ISSUE THREAD

**Issue by jmini** [BSI-Business-Systems-Integration-AG/demo-jhipster-democamp-2017#5]
I was looking at the generated DTOs in the generated TalkOrganizer Application. I do not understand why we sometime have 1 id or sometime 2 ids:

`ConferenceDTO`

* private Long id;
* private Long conferenceId;

`LocationDTO`

* private Long id;
* private Long locationId;

`SpeakerDTO`

* private Long id;

`TalkDTO`

* private Long id;

Is it because `id` always added by JHipster (maybe because a primary key is needed), even if not present in the `jdl` model? In this case `locationId` and `conferenceId` are probably redundant.

Thank you a lot for your explanations.

**Comment by colameo** [comment]
i removed the extra id's (they are not needed). pull from master.
